### ISSUE TITLE
Don't work right when select list have full value option

### ISSUE THREAD

**Issue by ryantrantan** [indrimuska/jquery-editable-select#1]
Hello,
I try with code : 
```html
<select id="my_select">
<option value="1">One</option>
<option value="2">Two</option>
</select>
```
On layout display then function work right but when submit form value get is one (not 1). this is not right when submit form.

Any idea to fix this ?
thank you

**Comment by indrimuska** [comment]
Hi @ryantrantan,
I haven't been notified about this issue, I'm sorry for getting into this so late.
However, jQuery Editable Select was one of my first plugins, and it was thought to have identical option text and value. It's kind of text input with suggestions as you type (typeahead), so you could have any value you type, even if it's not in the select list.

There are plenty of plugins doing what you're looking for, like brianreavis/selectize.js for jQuery or indrimuska/angular-selector for AngularJS.
