### ISSUE TITLE
dynamically add Select Options

### ISSUE THREAD

**Issue by rothmarkus86** [indrimuska/jquery-editable-select#11]
Hi,
is it possible to dynamically add / remove <Options> to the <Select> Elements?
If so, how can I do it?
I tried to ad <li> elements to the <ul> of the <input> --> but afterwards selection for those elements doesn´t work anymore.
Thanks!

**Comment by indrimuska** [comment]
Hi @rothmarkus86, I've just release a new Major version of the plugin that includes a method to add options to the dropdown list, like this:

```html
<select id="mySelect">
    <option>One</option>
</select>
```

```javascript
$('#mySelect').editableSelect();
$('#mySelect').editableSelect('add', 'Two');
```

Check out the new [README](https://github.com/indrimuska/jquery-editable-select/#editableselectadd-text--index--attrs--data--) to find out how it works now. ;)

**Comment by markusgit86** [comment]
Hi @indrimuska ,

thanks a lot!
Sry for the late response. I implemented it now and it works fine!

Kind regards,
Markus
