### ISSUE TITLE
Support submitting different text than is shown in the dropdown

### ISSUE THREAD

**Issue by 3noch** [indrimuska/jquery-editable-select#13]
I have a use-case where I want to show options like this:

  * 001 - User 1
  * 002 - User 2
  * 032 - User 3

But I only want to *submit* the `001` part of that. Is there a way to make the options in the dropdown differ from what is actually selected?

**Comment by indrimuska** [comment]
Well, you can listen to `select` event and change the input value using a regular expression like this:

```javascript
$('#myInput')
    .editableSelect()
    .on('select.editable-select', function (e, li) {
        var value = li.text().replace(/\s-.*$/, '')
        $('#myInput').val(value);
    });
```

Or you can set an attribute to your `<option>`s (i.e. `value`) and get the value after select:

```html
<select id="myInput">
    <option value="001">User 1</option>
    <option value="002">User 2</option>
    <option value="032">User 3</option>
</select>
```
```javascript
$('#myInput')
    .editableSelect()
    .on('select.editable-select', function (e, li) {
        var value = li.val();
        $('#myInput').val(value);
    });
```

**Comment by 3noch** [comment]
Awesome I'll give that a try.

**Comment by indrimuska** [comment]
I'm going to close this, feel free to re-open again if you encounter any problem! ;)
