### ISSUE TITLE
Disable autocomplete on input element

### ISSUE THREAD

**Issue by 3noch** [indrimuska/jquery-editable-select#14]
Chrome (and likely other browsers) want to help out by giving me autocomplete options on my editable select. But it obviously gets in the way with the editable select's features. Consider adding `autocomplete='off'` to the element when bound to it. I'm adding it manually now but I can't imagine a case where a user would want it in this case (because it messes with the dropdown).

**Comment by indrimuska** [comment]
Great tip! This will sure be part of the next release!
Thank you @3noch. :)

**Comment by indrimuska** [comment]
The fix for this issue has been released in version [2.0.1](https://github.com/indrimuska/jquery-editable-select/releases/tag/2.0.1).
