### ISSUE TITLE
event order issue

### ISSUE THREAD

**Issue by zswcorn** [indrimuska/jquery-editable-select#16]
when select "li" tag,sometimes the 'input' tag's 'blur' event will be fired before 'click' event , maybe better to use 'mousedown' event replace 'click' event and add e.preventDefault() in the 'mousedown' event handle function.

**Comment by indrimuska** [comment]
Hi @zswcorn, sorry for the late response and thank you for the advice!
Since I am not able to reproduce your issue, can you try just using the combination with mousedown on `<li>` and mouseup on `<ul>` (without preventing default event) if it works on your system?

```javascript
EditableSelectUtility.prototype.initializeList = function () {
	var that = this;
	that.es.$list
		.on('mousemove', 'li', function () {
			that.es.$list.find('.selected').removeClass('selected');
			$(this).addClass('selected');
		})
		.on('mousedown', 'li', function () {
			that.es.select($(this));
		})
		.on('mouseup', function () {
			that.es.$list.find('li.selected').removeClass('selected');
		});
};
```

**Comment by indrimuska** [comment]
Hi @zswcorn, are you able to reproduce this issue in the latest version [v2.2.0](https://github.com/indrimuska/jquery-editable-select/releases/tag/2.2.0)?

**Comment by zswcorn** [comment]
I'm really sorry that response too late,The project I was running has too many things to do in the last five weeks,So , I try the new version in chrome v54 and IE 11,It seems work now.The events are in the right order to fire.

**Comment by indrimuska** [comment]
Don't worry man! Happy to hear you've marked this issue! :)
