### ISSUE TITLE
Selection of elements in chrome browser via mouse cursor broken?

### ISSUE THREAD

**Issue by markusgit86** [indrimuska/jquery-editable-select#17]
Hi,

in the Chrome browser (V52.0.2743.116, Windows 8) I cannot select the elements of the editable select via the mouse cursor.

Selection via the arrow keys works fine.
Also selection in Firefox, on Safari (iPhone 6s) and Chrome on android works fine.

Regards,
Markus

**Comment by MarkiEC13** [comment]
Yes, I found the same issue without filter option. Sometimes it works when selecting multiple times, though.
Thanks

**Comment by elamprecht** [comment]
Have found the same issue by a user.  Digging into it, I concur with @MarkiEC13.  I have noticed, though, that the first item in the list is always selectable for me whereas the others in the list requires multiple attempts.  Keyboard always works.

**Comment by elamprecht** [comment]
For my usage, I changed one line in the code in the initializeList function:
   orig: .on('click', 'li', function () {
   new: .on('mousedown', 'li', function () {
This gives time to act on the mouse click down before the blur event occurs.

Ed

**Comment by indrimuska** [comment]
Thank you guys for reporting this!
Nice trick @elamprecht, let's go for it. I will add this in the next release. :)

**Comment by indrimuska** [comment]
This is now fixed in [v2.2.0](https://github.com/indrimuska/jquery-editable-select/releases/tag/2.2.0). Thanks
