### ISSUE TITLE
how to add themes

### ISSUE THREAD

**Issue by msouzarunner** [indrimuska/jquery-editable-select#2]
hi Indri Muska, great work if it included themes this plugin would be perfect.

**Comment by indrimuska** [comment]
OMG, @msouzarunner sorry for looking into this so far, I haven't received any notification about this issue. However you could simply change you css and specify any style you want to get the aspect you like. Have you already tried it?

**Comment by indrimuska** [comment]
I'm going to close this since it's not an issue of the plugin. Feel free to comment or open it again if you find any problem. :)
