### ISSUE TITLE
Key up/down shouldn't move cursor

### ISSUE THREAD

**Issue by BobDickinson** [indrimuska/jquery-editable-select#20]
When the list is open and the up/down arrow keys are being used to move through the list, those arrow keys should not be sent to the edit control (add e.preventDefault() in the handlers).  This will prevent the i-beam in the edit control from jumping between the beginning and end of the text as up/down are pressed.

**Comment by indrimuska** [comment]
Correct! Thanks @BobDickinson for reporting this, I'll patch it as soon as I can! :)

**Comment by indrimuska** [comment]
Fixed in [v2.2.0](https://github.com/indrimuska/jquery-editable-select/releases/tag/2.2.0), thanks @BobDickinson! :)
