### ISSUE TITLE
Option value

### ISSUE THREAD

**Issue by gzzz** [indrimuska/jquery-editable-select#22]
Is no support of value attribute of the option?

```
<select id="editable-select" name="…">
  <option value="1">Alfa Romeo</option>
  <option value="2">Audi</option>
  <option value="3">BMW</option>
  <option value="4">Citroen</option>
</select>
```
Could receive a value instead of option label.

**Comment by indrimuska** [comment]
Yes, using JS you can listen to the `select.editable-select` event.
More info at http://indrimuska.github.io/jquery-editable-select/, check for **Listen changes** section.

**Comment by gzzz** [comment]
Without event listener, just receive selected option value on form submit, like usual select do?

**Comment by indrimuska** [comment]
No, sorry you can't without the listener :(

**Comment by dsiqueira** [comment]
Try to use the following code $(".es-list .es-visible").val();

**Comment by fabiobraganet** [comment]
I lost my time
