### ISSUE TITLE
Allows selection of disabled options

### ISSUE THREAD

**Issue by kghandi** [indrimuska/jquery-editable-select#24]
EditableSelect.prototype.select should also check a.is("li[disabled]") in order to prevent selection of disabled options.

**Comment by indrimuska** [comment]
Hi @kghandi, you're absolutely right, thanks for reporting this, I'm going to fix it as soon as I can. :)

**Comment by indrimuska** [comment]
This is now fixed in [v2.2.2](https://github.com/indrimuska/jquery-editable-select/releases/tag/2.2.2).
At the moment I decided to keep disabled options in the list (with a different opacity style value), but maybe I can remove them at startup time.

**Comment by kghandi** [comment]
I think keeping disabled options with a different style is the right thing.  So long as they are not selectable.  

Removing them would not be the right thing.
