### ISSUE TITLE
If the value of option is different from the text, the value in request is the text, not the value

### ISSUE THREAD

**Issue by yangjin795** [indrimuska/jquery-editable-select#29]
If the value of option is different from the text, the value in request is the text, not the value
for example, the select is like this:

```
<select>
<option value="cat">lovely cat</option>
<option value="dog">lovely dog</option>
</select>
```

when use the editable select, if select the first option not enter text, the value in request is the "lovely cat" rather than "cat".  Bug value in request should to be "cat"

**Comment by indrimuska** [comment]
Hi @yangjin795, this behavior is how the project has been designed.
Anyway you can listen for `value`s, instead of texts, simply by listening the `select.editable-select` event.
Check out the **Listen changes** section in the [demo page](http://indrimuska.github.io/jquery-editable-select/).
