### ISSUE TITLE
Troubles with getting val() for option  tag

### ISSUE THREAD

**Issue by HmViper** [indrimuska/jquery-editable-select#3]
In your example onSelect with val() method you getting  text of "option" tag,but it must be a value of  tag.

**Comment by indrimuska** [comment]
Oh gosh, I haven't been notified of this issue, sorry for looking into this so late.
Anyway, as you can see, *jQuery Editable Select* is just a typeahead, it suggests words and auto-complete user inputs. It's not meant to return the corresponding value of a select. :)

**Comment by Langstra** [comment]
@indrimuska I would like to ask for this feature. This is how the combobox was meant I think and it is really useful.

**Comment by indrimuska** [comment]
Hi @Langstra, at the moment I don't have the time to implement that issue by myself, but I will be happy to review any PR you'd like to create.
