### ISSUE TITLE
Scroll not working if drag scroller by mouse button. 

### ISSUE THREAD

**Issue by klsdngr** [indrimuska/jquery-editable-select#31]
It works fine in chrome and firefox but when comes to IE it scroll not works. When we try to drag scroller by mouse it suddenly closes list but if we use mouse scroller to scroll list then only it stays at its position.

**Comment by klsdngr** [comment]
AnthonyBB changes solve this issue..!

**Comment by neskydul** [comment]
@klsdngr can you please tell me were the solution is? can't find those changes
