### ISSUE TITLE
Get the selected value on php

### ISSUE THREAD

**Issue by Baraw** [indrimuska/jquery-editable-select#33]
Hello,

When i try to get the value of my select via the GET method on php, i got the **option name**, _not the real value_. 
I tried without initialise the select with editable-select and it works.

## Example:
**Before:**
```
<select name="cars">
    <option value="1" >Alfa Romeo</option>
    <option value="2"  selected>Audi</option>
    <option value="3"  >BMW</option>
    <option value="4"  >Citroen</option>
</select>
[...]
echo $_GET['cars'] ; // shows"2"

```
**After**

```
<select name="cars"  id="editable-select">
    <option value="1" >Alfa Romeo</option>
    <option value="2"  selected>Audi</option>
    <option value="3"  >BMW</option>
    <option value="4"  >Citroen</option>
</select>
[...]
echo $_GET['cars'] ; // shows "Audi"

```

### How can i get the value number "2" using editable-select please ?

**Comment by indrimuska** [comment]
Check out "Listen changes" section in the [Demo page](http://indrimuska.github.io/jquery-editable-select/).
