### ISSUE TITLE
Keyboard Issue

### ISSUE THREAD

**Issue by XiyanHu** [indrimuska/jquery-editable-select#36]
It seems that the up and down array keys don't work correctly under this situation
![default](https://cloud.githubusercontent.com/assets/22786769/25778655/952ad59a-32b9-11e7-801d-5dcb37c0ee1a.png)

**Comment by indrimuska** [comment]
HI @XiyanHu, thanks for reporting this. Let me fix this in a minute..

**Comment by indrimuska** [comment]
This will be available in the next release
