### ISSUE TITLE
TypeScript Definitions available

### ISSUE THREAD

**Issue by baywet** [indrimuska/jquery-editable-select#43]
Hey,
Not an issue, more of a good news here.
I took the time to add typescript definitions for that package and the PR got accepted 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18356
https://www.npmjs.com/package/@types/jquery-editable-select
Maybe the documentation could be updated to provide that information as well?

**Comment by indrimuska** [comment]
Thanks @baywet for you time, I'll do it in a minute!
