### ISSUE TITLE
the plugin jquery-editable-select doesn't work on modal-dialog

### ISSUE THREAD

**Issue by zhuliuw** [indrimuska/jquery-editable-select#5]
Hi ,
this plugin is really great, but looks like it doesn't work on bootstrap modal-dialog, when I use a selector in bootstrap modal-dialog, I verified it did not work on bootstrap modal-dialog, I am pretty new to jquery, could u please tell me how to fix this issue, thanks a lot!

paste the testing code:
<div >
				    <button id="mdl-engine-confirm" type="button" class="btn btn-primary" onClick="showup();">show</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
<div >
				    <button id="mdl-engine-confirm" type="button" class="btn btn-primary" onClick="showup();">show</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>

		<div class="modal fade" id="triggerMdlEngineModal">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">
						<span aria-hidden="true">&times;</span>
						<span class="sr-only">Close</span>
					</button>
					<h4 class="modal-title" id="triggerEngineModalLabel"></h4>
				</div>
				<div class="modal-body">
					<div class="container-fluid">
						<div class="row_fluid">
							<form role="form" class="form-horizontal">
							  <div class="form-group" id="mdl-edit-div">
									<label class="col-lg-2 control-label">ID</label>
									<div class="col-lg-2">
										<input id="mdl-id-trigger" class="form-control" disabled></input>
									</div>
									<label class="col-lg-3 control-label">Name</label>
									<div class="col-lg-5">
										<input id="mdl-name-trigger" class="form-control" disabled></input>
									</div>
								</div>
								<div class="form-group">
									<label class="col-lg-3 control-label">Source File Selection</label>
									<div class="col-lg-9">
                                       <select id="mdl-sourcefile-selector" class="form-control">
                                       <option>/tep/modeleng/sourcefile/sourcefile1.data</option>
                                       <option>/tep/modeleng/sourcefile/sourcefile2.data</option>
                                       <option>/tep/modeleng/sourcefile/sourcefile3.data</option>
                                       <option>/tep/modeleng/sourcefile/sourcefile4.data</option>
                                       <option>/tep/modeleng/sourcefile/sourcefile5.data</option>
                                       <option>/tep/modeleng/sourcefile/sourcefile6.data</option>
                                       <option>/tep/modeleng/sourcefile/sourcefile7.data</option>
                                       </select>
									</div>
								</div>
										<div class="row-fluid">
					<div class="span4">Into this</div>
					<div class="span7">
						<select id="basic">
							<option>Alfa Romeo</option>
							<option>Audi</option>
							<option>BMW</option>
							<option>Citroen</option>
							<option>Fiat</option>
							<option>Ford</option>
							<option>Jaguar</option>
							<option>Jeep</option>
							<option>Lancia</option>
							<option>Land Rover</option>
							<option>Mercedes</option>
							<option>Mini</option>
							<option>Nissan</option>
							<option>Opel</option>
							<option>Peugeot</option>
							<option>Porsche</option>
							<option>Renault</option>
							<option selected="selected">Smart</option>
							<option>Volkswagen</option>
							<option>Volvo</option>
						</select>
					</div>
				</div>
								<div class="form-group">
									<label class="col-lg-3 control-label">Landing Host</label>
									<div class="col-lg-9">
									<div id="mdl-landing-hose"></div>
									</div>
								</div>
								<div class="form-group">
									<label class="col-lg-3 control-label">Landing Folder</label>
									<div class="col-lg-9">
										<input id="mdl-land-folder" class="form-control"></input>
									</div>
								</div>
								<div class="form-group">
									<label class="col-lg-3 control-label">Execution Command</label>
									<div class="col-lg-9">
										<input id="mdl-command-trigger" class="form-control" disabled></input>
									</div>
								</div>
								<div class="form-group">
					               	<label class="col-lg-3 control-label">Parameters</label>
					               <table id="paraTable1">
					                  <tr class="col-lg-12 control-label">
					                   <td><input maxlength="100" type="text" class="form-control" id="model-para-name1[]" value=""></td>
					                   <td><input maxlength="100" type="text" class="form-control" id="model-para-value1[]" value=""></td>
					                   <td><a href="javascript:void(0);" class="add">+</a></td>
					                 </tr>
					               </table>
			                    </div>
							</form>
						</div>
					</div>
				</div>
				</div>
				</div>
				</div>
				</div>

	<script>
			window.onload = function () {
				$('#basic1').editableSelect();
				$('#mdl-sourcefile-selector1').editableSelect();
		}
		function showup(){
		$('#basic').editableSelect();
		$('#mdl-sourcefile-selector').editableSelect();
		$('#triggerMdlEngineModal').modal({ 
        show: true
    }); 
		}
		</script>

**Comment by narigondelsiglo** [comment]
Try modifying in CSS the z-index of the UL object. Inspect the code in the browser to know what CSS class you need to fix.

**Comment by indrimuska** [comment]
Sorry for coming into this so late, I was not notified about any issue of the project.
Anyway, as @narigondelsiglo already said (thank you :), to solve this problem you need to change the css `z-index` of the `.es-list` element. Since twitter bootstrap's modals z-index has a default value to 1050, the minimum value to view the list is 1051 (you can also set it to 1050, but it may not work under certain conditions).

This fiddle shows how to solve your issue:
https://jsfiddle.net/s1mcupjh/

**Comment by indrimuska** [comment]
FYI now the plugin has a new `appendTo` property to set where to insert the dropdown list in the DOM.
