### ISSUE TITLE
created.editable-select  event not working

### ISSUE THREAD

**Issue by voltwu** [indrimuska/jquery-editable-select#79]
I followed the [demo](https://github.com/indrimuska/jquery-editable-select). 

I made an example on [Fiddle](https://jsfiddle.net/atqw02fv/25/).

And I am testing the `created.editable-select` event, which should be fired when the load finished. But, it doesn't invoke my method `console.log("ok")`.

My Html Code:
```
<li>
  <select id="editable-select" class="form-control filteropt">
    <option text="{1}({2})" data-fieldval="{1}">456</option>
    <option text="{1}({2})" data-fieldval="{1}">123</option>
</select>
</li>
```
MY JS Code:
```
$('#editable-select')
.editableSelect({ filter: false})
.on('created.editable-select', function () {
    console.log("ok");
});
```
![kLJrx](https://user-images.githubusercontent.com/45677662/110197999-2f5ad280-7e8a-11eb-82aa-73a75843f65a.png)

Is this a bug?

**Comment by mannyvergel** [comment]
I encounter the same thing for all the triggers of editable-select

**Comment by wannadream** [comment]
I haven't had time to resolve this throughly yet, but I do have a workaround if you would like: https://stackblitz.com/edit/jquery-editable-select-created-event

**Comment by wannadream** [comment]
I pushed a solution for this. Please see updated READNE. You need to register event handlers before initializing the editable select.
