### ISSUE TITLE
Feature request: ability to choose where to append the dropdown list

### ISSUE THREAD

**Issue by nikodz** [indrimuska/jquery-editable-select#8]
Hello,

First of all, this is really nice plugin.

The problem I've faced is that I'm using editable select in dialog, which is removed from dom after closing. But, because this plugin's making _&lt;ul&gt;_ in body, it stays there.

It will be good, either if I'll be able to call something which will dispose specific 'editable select' or have reference on that _&lt;ul&gt;_ tag.

**Comment by indrimuska** [comment]
Yeah, that would be great if there'll be a new `appendTo` property to choose where to append the list. At the moment you can change your stylesheet as in #5.

**Comment by nikodz** [comment]
`appendTo` is good, but when I changed it to my dialogs body, list lost position.

**Comment by indrimuska** [comment]
Ok @nikodz, I've just updated the plugin and created a new example for dialogs.
Check out the example directory.

**Comment by nikodz** [comment]
Thanks,  4492ef4 fixed that :)
