### ISSUE TITLE
serious issues!

### ISSUE THREAD

**Issue by REDAL** [indrimuska/jquery-editable-select#83]
Hi community @AnthonyBB  @indrimuska  @wannadream 

first, I want to thank you for editable-select, it really simply selects, and makes them more useful.

simply, when I tried to disable the filter, it shows the whole list, but when u click on an option, it does not disappear.

also, I tried a lot of solutions, to make the list shows just under the textbox, but not working

if you can help me, it will be greatly appreciated.

I have created a video where I show, the wrong position within a table, and also, when clicking on the option, the list does not disappear, when the filter is disabled.

also, when initializing dynamically added select lists, it does not initialize the options list

please note: I am using editable-select, in HTML table, with data repeater

https://user-images.githubusercontent.com/7544360/177603088-f11628ba-784f-414c-b9f5-b19bdcd7b0d1.mp4

**Comment by wannadream** [comment]
I am not sure what are you trying to achieve. Since it is open-sourced, you can modify it to the way you want.
